name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - master
      - deploy-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Invoke Webpack build
      run: |
        npm install .
        npm run build
    - name: Invoke Deployment
      env:
        BUILD_DIR: dist
      uses: maxheld83/ghpages@v0.2.1
